- hosts: hadoop_slave
  tasks:
  - copy:
          src: /root/hadoop-1.2.1-1.x86_64.rpm
          dest: /root

  - copy:
          src: /root/jdk-8u171-linux-x64.rpm
          dest: /root

  - shell: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
          
  - shell: "rpm -ivh jdk-8u171-linux-x64.rpm --force"

  - file:
          path: /nn
          state: directory

  - template:
          src: /hadoop/slave/hdfs-site.xml
          dest: /etc/hadoop

  - template:
          src: /hadoop/slave/core-site.xml
          dest: /etc/hadoop


  - shell: "hadoop-daemon.sh start datanode"
